# Generated by Django 5.0.1 on 2024-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='WatchedMovie',
        ),
    ]
