# Generated by Django 5.0.1 on 2024-05-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_watchedmovie_delete_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchedMovie',
        ),
    ]
