# Generated by Django 5.0.1 on 2024-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='movie_id',
            field=models.FloatField(),
        ),
    ]
