# Generated by Django 5.0.1 on 2024-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usermovie_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
